version: "3.8"
services:
  dev:
    build:
      context: .
      target: dev
    restart: always
    command: npm start
    environment:
      - NODE_ENV=development
    volumes:
      - .:/dark-pref
      - /dark-pref/node_modules/
    ports:
      - 8888:8888
